### ISSUE TITLE
[Bug Report?] DeathPenalty - Accumulated experience is lost on death with SkillLostPercent at 0 (skill loss disabled)

### ISSUE THREAD

**Issue by Abbanon** [CrystalFerrai/ValheimMods#22]
As the title says, I'm not sure if this is a bug or intended behaviour with the DeathPenalty mod, so I'm posting just in case.
When `SkillLossPercent` is set to `0` (disabled), levels do not decrease on death, as intended.
However, any accumulated XP towards the next level *is* lost on death.

**Comment by CrystalFerrai** [comment]
I don't know why this might be happening, most likely due to a change in game code since this mod was written. I will look into it next time I get a chance, but I cannot say for sure when that will be. If possible, I will add a config option to lose all exp in current level instead of losing a percentage so people can configure it either way they want.

**Comment by CrystalFerrai** [comment]
I finally got back to this. Death Penalty version 1.1.0 now has a config option called `ResetLevelProgress` which controls whether skill progress towards the next level is reset when dying. Defaults to `true`.
