### ISSUE TITLE
Cartography skill incompat

### ISSUE THREAD

**Issue by benjdidj** [CrystalFerrai/ValheimMods#3]
https://www.nexusmods.com/valheim/mods/394

This  mod add a skill that increase your minimap vision the more you explore. It  is possible to set up base  in the mod's config. 
Your mod seem to overwrite the changes done by this mod and take the base value in your mod's config. 
I wish your mod could take the modified vision value, in ither words :
Would there be a way to keep the growing minimap view from cartography  while  using your mods to enhance the way  you can actually explore it(better view, item,weather etc.)

Just for u to have an idea, the config from Cartography skill  

[advize.CartographySkill - Copie.txt](https://github.com/CrystalFerrai/ValheimMods/files/6244315/advize.CartographySkill.-.Copie.txt)

👍Thx for your mod.

**Comment by CrystalFerrai** [comment]
It looks like that mod updates the explore radius variable while this mod tells the game to not use the variable at all but call a mod function instead. So, they are not really compatible. Both mods are expecting to have full control over the explore radius. It just happens that the way this one is implemented will cause the other to have no effect. I cannot think of any clean way for them to work together because neither can tell what the other is doing or if the other is even installed.

**Comment by benjdidj** [comment]
Thx for your answer.ill have to choose then. Thx for your work
